Basics
js-tasks-ru/vue-20220419_sword-and-brush pull request #1
Opened 2022-04-28 17:20 UTC by Red-Warrior

2022-04-28 19:04 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-04-28 19:09 UTC, ShGKme requested changes
В 01-basics/03-MarkedList требуется явно реализовать вычисляемое свойство, остальные задачи приняты.

2022-04-28 19:09 UTC, ShGKme commented on 01-basics/02-VueCalculator/script.js
> +  },
Если константа не нужна в шаблоне, а нужна только в JS коде, её можно описывать, как обычную константу вне компонента, не помещая в `this.$options`. "Костыль" c `$options` используется, когда надо константу сделать доступной в шаблоне.

2022-04-28 19:09 UTC, ShGKme commented on 01-basics/03-MarkedList/script.js
> +});
Здесь через `watch` реализовано вычисляемое свойство `restructuredEmails`. Вычисляемые свойства лучше явно реализовывать через `computed`. так будет и явно видно, что `restructuredEmails` - не самостоятельное свойство, а вычисляющееся, и решение будет работать даже если потребуется поддержка обновления списка `email`-ов.

2022-05-08 12:46 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-05-08 12:47 UTC, ShGKme requested changes
Изменения приняты, но решены не все добавленные в PR задачи

2022-05-12 12:38 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-05-12 12:41 UTC, merged