Wrappers, Forms
js-tasks-ru/vue-20220419_sword-and-brush pull request #4
Opened 2022-06-06 18:01 UTC by Red-Warrior

2022-06-06 18:02 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-06-07 10:11 UTC, ShGKme requested changes
Требуется небольшое изменение в `06-wrappers/01-UiLink` по комментариям.
Остальные задачи приняты

2022-06-07 10:11 UTC, ShGKme commented on 06-wrappers/01-UiLink/components/UiLink.vue
> +
Вместо импорта `RouterLink` лучше оставить возможность передавать его, или использовать строку с зарегистрированным именем. Так компонент можно будет использовать и в проекте без `VueRouter` для обычных ссылок. Сейчас же компонент напрямую зависит от роутера и требует его, как зависимость, будет включать его в себя.

2022-06-14 15:21 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-06-14 15:26 UTC, ShGKme approved these changes
Все задачи приняты 👍

2022-06-14 15:28 UTC, merged